Render latex on php mode
wiris/moodle-filter_wiris pull request #162
Opened 2024-10-09 14:51 UTC by xjiang-at-wiris

## Description

> Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change. Include, if necessary, a description of the proposed solution and the reasoning behind it.

The ability of MathType to render LaTeX was removed at some point, and now it needs to be added back.

## Type of Change

> Please delete options that are not relevant.

- [ ] Feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (non-breaking change that doesn't add any functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes to documentation only)
- [ ] Refactoring (non-breaking change that improves the code structure)

## How should be tested? (Manual or Automated Tests)
 
- Launch moodle
- Enure your render type is PHP ([link](http://localhost:8000/admin/search.php?query=render+type))
- Write MathML and LateX son some page
- Play with `wiriseditorparselatex` parameter (true or false)
   - On file `configuration.ini` 
- Play with Mathjax priority [Link](http://localhost:8000/admin/filters.php)
Compare the results; they should follow the result shown in the table.

| ID | Render | wirisparselatex                 | MathJax        | Latex Renderer Expected |
|----|--------|----------------------------------|----------------|-------------------------|
| 1  | PHP    | TRUE                             | Priority over MathType | MathJax                |
| 2  | PHP    | TRUE                             | MathType has priority  | MT                     |
| 3  | PHP    | TRUE                             | Disabled       | MT                      |
| 4  | PHP    | FALSE                            | Priority over MathType | MathJax                |
| 5  | PHP    | FALSE                            | MathType has priority  | MathJax                |
| 6  | PHP    | FALSE                            | Disabled       | No render              |

[Task  #50947](https://wiris.kanbanize.com/ctrl_board/2/cards/50947/details/)

2024-10-09 15:05 UTC, jgonzalez-at-wiris approved these changes
No lo he probado, pero a nivel de código me parece que está genial! Gran trabajo Xinyu!

2024-10-09 15:05 UTC, jgonzalez-at-wiris commented on subfilters/php.php
> -
¿Por qué has quitado el salto de línea? 😢 😂

2024-10-09 15:15 UTC, xjiang-at-wiris commented on subfilters/php.php
> -
Puse un echo para ver el resultado jajaja, voy a ponerlo de vuelta

2024-10-09 16:07 UTC, usantos-at-wiris requested changes

2024-10-09 16:07 UTC, usantos-at-wiris commented on subfilters/php.php
> +        // find LateX
```suggestion
        // Find LateX.
```

2024-10-09 16:07 UTC, usantos-at-wiris commented on subfilters/php.php
> +        // If MathJax don't have preference and wiriseditorparselatex = true, parse LateX into MathML
```suggestion
        // If MathJax don't have preference and wiriseditorparselatex = true, parse LateX into MathML.
```

2024-10-09 16:22 UTC, jgonzalez-at-wiris commented on subfilters/php.php
> +        // If MathJax don't have preference and wiriseditorparselatex = true, parse LateX into MathML
```suggestion
        // If MathJax doesn't have preference and wiriseditorparselatex = true, parse LateX into MathML
```

2024-10-10 10:50 UTC, carla-at-wiris approved these changes

2024-10-31 09:43 UTC, merged